### ISSUE TITLE
unable to run the code

### ISSUE THREAD

**Issue by sam7418** [dwave-examples/maximum-cut#18]
I am using windows 10. Could not run the code. Getting some ValueError. 
I am getting this error for both `maximum_cut_ising.py` and `maximum_cut.py`
Would appreciate your help.Thanks. 

```
Traceback (most recent call last):
  File ".\maximum_cut_ising.py", line 47, in <module>
    sampler = EmbeddingComposite(DWaveSampler())
  File "C:\Users\sam\Anaconda3\envs\modern-apis-with-fastapi-main\lib\site-packages\dwave\system\samplers\dwave_sampler.py", line 142, in __init__
    self.client = Client.from_config(**config)
  File "C:\Users\sam\Anaconda3\envs\modern-apis-with-fastapi-main\lib\site-packages\dwave\cloud\client\base.py", line 360, in from_config
    return _clients[_client](**config)
  File "C:\Users\sam\Anaconda3\envs\modern-apis-with-fastapi-main\lib\site-packages\dwave\cloud\events.py", line 105, in wrapped
    rval = fn(*pargs, **kwargs)
  File "C:\Users\sam\Anaconda3\envs\modern-apis-with-fastapi-main\lib\site-packages\dwave\cloud\client\base.py", line 453, in __init__
    raise ValueError("API token not defined")
ValueError: API token not defined

```

**Comment by davage** [comment]
Hello,

In order to run the code, you need to have a Leap account:
https://cloud.dwavesys.com/leap/signup/

In your Leap account, you can get an API Token which will give you access to the QPU via the SAPI endpoint.

The easiest way to get started running the code is by using the Leap IDE once you have signed in:
https://ide.dwavesys.io/workspaces/

You can learn more about installing and running the D-Wave Ocean Tools and about the Leap IDE through our Learn to Swim video series:
https://www.youtube.com/playlist?list=PLPvKnT7dgEsuhec_yW9oxcZ6gg9SfRFFV

Feel free to reach out to us with any questions through Leap using the support features offered there.
